apiVersion: v1
kind: Namespace
metadata:
  name: hello-ps
  labels:
    team: prod-team
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello-ps
  labels:
    app: hello-python
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: hello-python
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
  namespace: hello-ps
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - image: ghcr.io/argosenpaikun/nica-python-kube:latest
          name: hello-python
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}